### ISSUE TITLE
Cron spec issue

### ISSUE THREAD

**Issue by danharper83** [platformsh-templates/magento2ce#9]
Hi,

When I use the default cron spec in the template it won't push up due to the following error message.

"The minimum interval between cron runs is 5 minutes, even if specified as less."

I guess because the cron spec in the platform.app.yml is 

```
crons:
    magento:
        spec: "* * * * *"
        cmd: "php bin/magento cron:run"
```

Should it not be?

```
crons:
    magento:
        spec: "*/5 * * * *"
        cmd: "php bin/magento cron:run"

```
Cheers Dan
